# Setup

Clone repo, install dependencies and check PyTorch and GPU.

In [1]:
!git clone https://github.com/parthbansal05/tempyolo  # clone
%cd tempyolo
%cd yolov5
%pip install -qr requirements.txt  # install

import torch
import utils
display = utils.notebook_init()  # checks

YOLOv5 🚀 2022-6-8 torch 1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)


Setup complete ✅ (2 CPUs, 12.7 GB RAM, 38.7/78.2 GB disk)


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 1. Inference

`detect.py` runs YOLOv5 inference on a variety of sources, downloading models automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases), and saving results to `runs/detect`. Example inference sources are:

```shell
python detect.py --source 0  # webcam
                          img.jpg  # image 
                          vid.mp4  # video
                          path/  # directory
                          path/*.jpg  # glob
                          'https://youtu.be/Zgi9g1ksQHc'  # YouTube
                          'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```

In [3]:
from PIL import Image
from numpy import asarray
from det import *
  
img = Image.open('/content/tempyolo/TrainingDataset/images/train/photo_2022-04-07_01-17-14.jpg')
numpydata = asarray(img)

data=detect_preloaded(  weights="/content/drive/MyDrive/bestt.pt",
              source=numpydata,
              data="/content/tempyolo/yolov5/data/custom.yaml"
           )
print(data)

YOLOv5 🚀 2022-6-8 torch 1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)



(1280, 960, 3)


Fusing layers... 
Model summary: 213 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs


(['phone', 'pen'], [[0.3005208373069763, 0.671875, 0.528124988079071, 0.21718749403953552], [0.4140625, 0.345703125, 0.3322916626930237, 0.18203124403953552]], ['0.58', '0.60'])


In [4]:
from det import *
data=detect(  weights="/content/drive/MyDrive/bestt.pt",
              source="/content/tempyolo/TrainingDataset/images/train/photo_2022-04-07_01-17-14.jpg",
              data="/content/tempyolo/yolov5/data/custom.yaml"
           )
print(data)

YOLOv5 🚀 2022-6-8 torch 1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)

Fusing layers... 
Model summary: 213 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs


([[0.4541666805744171, 0.3218750059604645, 0.34375, 0.22499999403953552], [0.26354166865348816, 0.676562488079071, 0.43958333134651184, 0.21718749403953552]], ['pen 0.65', 'phone 0.69'])


In [ ]:
from detectCordLable import *
run(    weights="/content/tempyolo/bestt.pt",
        source="/content/tempyolo/TrainingDataset/images/train/photo_2022-04-07_01-17-25.jpg",
        data="/content/tempyolo/yolov5/data/custom.yaml"
    )

In [12]:
!python detectCordLable.py --weights /content/tempyolo/bestt.pt --conf 0.25 --source /content/tempyolo/TrainingDataset/images/train --data /content/tempyolo/yolov5/data/custom.yaml
# display.Image(filename='runs/detect/exp/zidane.jpg', width=600)

parameters: 
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, data='/content/tempyolo/yolov5/data/custom.yaml', device='', dnn=False, exist_ok=False, half=False, hide_conf=False, hide_labels=False, imgsz=[640, 640], iou_thres=0.45, line_thickness=3, max_det=1000, name='exp', nosave=False, project=PosixPath('runs/detect'), save_conf=False, save_crop=False, save_txt=False, source='/content/tempyolo/TrainingDataset/images/train', update=False, view_img=False, visualize=False, weights=['/content/tempyolo/bestt.pt'])
YOLOv5 🚀 2022-6-8 torch 1.11.0+cu113 CUDA:0 (Tesla T4, 15110MiB)

Fusing layers... 
Model summary: 213 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
dataset<utils.datasets.LoadImages object at 0x7f1e628d5c10>

im
[[[ 32  32  33 ...  44  41  42]
  [ 33  33  33 ...  40  42  43]
  [ 34  34  34 ...  41  44  41]
  ...
  [ 69  71  70 ... 126 123 123]
  [ 76  73  73 ... 127 127 122]
  [ 74  68  70 ... 125 127 122]]

 [[ 63  63  64 ...  33  30  31]
  [

# 3. Train


In [ ]:
# Tensorboard  (optional)
%load_ext tensorboard
%tensorboard --logdir runs/train

In [ ]:
# Train YOLOv5s on COCO128 for 3 epochs
!python /content/tempyolo/yolov5/train.py --img 640 --batch 16 --epochs 100 --data /content/tempyolo/yolov5/data/custom.yaml --weights /content/tempyolo/yolov5/yolov5s.pt --cache